syntax = "proto3";

package cypherlabs.postgres.scale.postgresmanager;

service PostgresManager {
    rpc StartPrimary (StartPrimaryRequest) returns (StartPrimaryResponse);
    rpc CreateReplicationSlot (CreateReplicationSlotRequest) returns (CreateReplicationSlotResponse);
    rpc StartReplica (StartReplicaRequest) returns (StartReplicaResponse);
}

message StartPrimaryRequest {
    string data_dir = 1;
    uint32 port = 2;
}

message StartPrimaryResponse {
    uint32 pid = 1;
}

message CreateReplicationSlotRequest {
    string slot_name = 1;
}

message CreateReplicationSlotResponse {
    string lsn = 1;
}

message StartReplicaRequest {
    string data_dir = 1;
    uint32 port = 2;
    string primary_host = 3;
    uint32 primary_port = 4;
    string slot_name = 5;
}

message StartReplicaResponse {
    uint32 pid = 1;
}